#!/data/data/com.termux/files/usr/bin/bash
clear
play -q $HOME/JARVIS/sound/hello.mp3 &>/dev/null &
bash $HOME/JARVIS/logo2.sh
play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null &
echo $q $b"╔══════════════════════════════════════════════════╗$b"
echo $q $b"║$b [$m •$b ]$p Notifikasi  $m  :$k Selamat$m $ucapan$k !$b          $b  ║"
echo $q $b"║$b [$k •$b ]$p Sekarang Jam$m  :$k $(date +"%H:%M")                     $b ║"
echo $q $b"║$b [$h •$b ]$p Sekarang Hari$m :$k $ucap,$tanggal$b$b    ║"
echo $q $b"║$b [$bl •$b ]$p Penguna total$m :$k $random_number                       $b ║"
echo $q $b"╚══════════════════════════════════════════════════╝$b$h"
