#!/data/data/com.termux/files/usr/bin/bash
clear
q="-e"
e="echo "
s="sleep 1"
ss="sleep 2"
sss="sleep 3"
v="4.2.0"
m="\033[1;31m"
h="\033[1;32m"
k="\033[1;33m"
b="\033[1;34m"
bl="\033[1;36m"
p="\033[1;37m"
bash $HOME/JARVIS/logo2.sh
play -q $HOME/JARVIS/sound/hello.mp3 &>/dev/null &
play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null &
echo $q $b"╔══════════════════════════════════════════════════╗$b"
echo $q $b"║$b [$m •$b ]$p Notifikasi  $m  :$k Selamat$m $ucapan$k !$b          $b  ║"
echo $q $b"║$b [$k •$b ]$p Sekarang Jam$m  :$k $(date +"%H:%M")                     $b ║"
echo $q $b"║$b [$h •$b ]$p Sekarang Hari$m :$k $ucap,$tanggal$b$b    ║"
echo $q $b"║$b [$bl •$b ]$p Penguna total$m :$k $random_number                       $b ║"
echo $q $b"╚══════════════════════════════════════════════════╝$b$h"
