#!/data/data/com.termux/files/usr/bin/bash

mv /$HOME/JARVIS/musik.sh /$HOME/JARVIS/off.sh
killall play
play -q $HOME/JARVIS/sound/oke.mp3 &>/dev/null
play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null
clear
